exports.up = function(knex) {
  return knex.schema
    .createTable('formas_pagto', function(table) {
      table.string('codigo').primary();
      table.date('dt_inc');
      table.integer('cod_usr_inc');
      table.date('dt_alt');
      table.integer('cod_usr_alt');
      table.date('dt_exc');
      table.integer('cod_usr_exc');
      table.string('cod_empresa');
      table.string('descricao');
      table.string('tipo_forma');
      table.boolean('mostra_crcp');
      table.string('gera_boleto', 1);
      table.string('cheque', 1);
      table.string('cod_tipo_cobranca');
      table.string('cartao', 1);
      table.decimal('spread', 10, 2);
      table.string('recebimento', 1);
      table.integer('prazo');
      table.string('tipo');
      table.string('cod_cliente');
      table.string('cod_conta_bancaria');
      table.string('forma_arq_retorno', 1);
      table.string('mostra_cpcr', 1);
      table.string('gerar_cr', 1);
      table.string('gerar_cr_baixa', 1);
      table.string('gerar_cx', 1);
      table.decimal('vl_minimo_parcela', 10, 2);
      table.string('descricao_cupom');
      table.string('cod_conta_corrente_transf');
      table.string('cod_portador');
      table.string('cod_tipo_pagto_sat');
      table.string('sinc_mobile', 1);
      table.string('hist_baixa_padrao');
      table.string('id_site');
      table.string('cod_cond_pagto_site');
      table.string('cod_situacao_cobranca');
      table.string('gerar_cr_baixado', 1);
      table.string('pagamento_produtor', 1);
      table.string('cnpj_operadora');
      table.string('bandeira_cartao');
      table.string('obriga_nsu', 1);
      table.decimal('perc_desc_esp', 10, 2);
      table.string('sinc_cobranca', 1);
      table.string('obs_mobile');
      table.string('usa_tef', 1);
      table.string('cod_bandeira_tef');
      table.string('bandeira_tef');
      table.decimal('vl_parc_min_cred', 10, 2);
      table.decimal('vl_parc_min_deb', 10, 2);
      table.decimal('taxa_fixa', 10, 2);
      table.string('informa_dt_vencto_nfe', 1);
      table.string('vale_presente', 1);
      table.integer('ciclos_troca');
      table.string('desc_site');
      table.boolean('integracao_pix_imediato');
      table.decimal('valor_minimo_pix_imediato', 10, 2);
      table.string('empresas');
      table.boolean('gerar_qrcode_antes_faturamento');
      table.decimal('taxa_pix', 10, 2);
      table.boolean('utilizar_dt_vencto_baixa');
      table.string('cod_fornecedor');
      table.boolean('utilizar_saldo_cashback');
      table.decimal('perc_acre', 10, 2);
      table.string('baixa_vendedor', 1);
      table.string('gerar_cr_adiantamento', 1);
      table.timestamps(true, true);
    })
    .createTable('cond_pagto', function(table) {
      table.string('codigo').primary();
      table.date('dt_inc');
      table.integer('cod_usr_inc');
      table.date('dt_alt');
      table.integer('cod_usr_alt');
      table.date('dt_exc');
      table.integer('cod_usr_exc');
      table.string('cod_empresa');
      table.string('descricao');
      table.integer('parcelas');
      table.integer('p1');
      table.integer('p2');
      table.integer('p3');
      table.integer('p4');
      table.integer('p5');
      table.integer('p6');
      table.integer('p7');
      table.integer('p8');
      table.integer('p9');
      table.integer('p10');
      table.integer('p11');
      table.integer('p12');
      table.decimal('desconto', 10, 2);
      table.decimal('acrescimo', 10, 2);
      table.decimal('vl_minimo', 10, 2);
      table.decimal('vl_maximo', 10, 2);
      table.string('tipo');
      table.string('forma_recebto');
      table.string('at_preco', 1);
      table.integer('cod_status');
      table.integer('dia_vencto_parc');
      table.integer('p13');
      table.integer('p14');
      table.integer('p15');
      table.integer('p16');
      table.integer('p17');
      table.integer('p18');
      table.integer('p19');
      table.integer('p20');
      table.integer('p21');
      table.integer('p22');
      table.integer('p23');
      table.integer('p24');
      table.integer('periodo_de1');
      table.integer('periodo_ate1');
      table.integer('dia_vencto_periodo1');
      table.integer('periodo_de2');
      table.integer('periodo_ate2');
      table.integer('dia_vencto_periodo2');
      table.integer('periodo_de3');
      table.integer('periodo_ate3');
      table.integer('dia_vencto_periodo3');
      table.integer('periodo_de4');
      table.integer('periodo_ate4');
      table.integer('dia_vencto_periodo4');
      table.string('pessoa');
      table.decimal('desconto_2', 10, 2);
      table.string('preco');
      table.string('gera_comissao', 1);
      table.string('sinc_mobile', 1);
      table.integer('ordem');
      table.string('prazo_prim_parc_manual', 1);
      table.integer('p25');
      table.integer('p26');
      table.integer('p27');
      table.integer('p28');
      table.integer('p29');
      table.integer('p30');
      table.integer('p31');
      table.integer('p32');
      table.integer('p33');
      table.integer('p34');
      table.integer('p35');
      table.integer('p36');
      table.integer('dia_corte');
      table.integer('dias_faturamento');
      table.timestamps(true, true);
    });
};

exports.down = function(knex) {
  return knex.schema
    .dropTableIfExists('cond_pagto')
    .dropTableIfExists('formas_pagto');
};